[profile.default]
retries = 0
failure-output = "immediate"

[profile.integration]
retries = 0
test-threads = 2

[profile.ci]
retries = 1
test-threads = 2
failure-output = "immediate"
fail-fast = false
