export type ThemeMode = "dark" | "light";
export type UiLanguage = "zh" | "en";

export const translations = {
  title: { zh: "WeChatBot 管理后台", en: "WeChatBot Web Admin" },
  tokenLabel: { zh: "Bearer 令牌", en: "Bearer token" },
  saveToken: { zh: "保存令牌", en: "Save token" },
  loadData: { zh: "刷新数据", en: "Load data" },
  loading: { zh: "加载中...", en: "Loading..." },
  theme: { zh: "主题", en: "Theme" },
  dark: { zh: "深色", en: "Dark" },
  light: { zh: "浅色", en: "Light" },
  language: { zh: "语言", en: "Language" },
  chinese: { zh: "中文", en: "Chinese" },
  english: { zh: "英文", en: "English" },
  overview: { zh: "概览", en: "Overview" },
  totalBots: { zh: "Bot 总数", en: "Total Bots" },
  onlineBots: { zh: "在线 Bot", en: "Online Bots" },
  messagesTodayTotal: { zh: "今日消息总数", en: "Total Messages Today" },
  forwardFailuresTodayTotal: { zh: "今日转发失败总数", en: "Total Forward Failures Today" },
  noOverviewData: { zh: "暂无概览数据", en: "No overview data." },
  bots: { zh: "Bots", en: "Bots" },
  createBot: { zh: "创建 Bot", en: "Create Bot" },
  botId: { zh: "Bot ID", en: "Bot ID" },
  status: { zh: "状态", en: "Status" },
  heartbeat: { zh: "心跳", en: "Heartbeat" },
  botMessagesToday: { zh: "今日消息数", en: "Messages Today" },
  botForwardFailures: { zh: "转发失败数", en: "Forward Failures" },
  action: { zh: "操作", en: "Action" },
  noBots: { zh: "暂无 Bot", en: "No bots available." },
  select: { zh: "选择", en: "Select" },
  selectedBot: { zh: "当前 Bot", en: "Selected Bot" },
  runtime: { zh: "运行时", en: "Runtime" },
  scanToLogin: { zh: "请使用微信扫码登录", en: "Please scan with WeChat to sign in" },
  qrUnavailable: { zh: "当前暂无可用二维码，请稍后刷新。", en: "QR code is unavailable. Please refresh later." },
  yes: { zh: "是", en: "yes" },
  no: { zh: "否", en: "no" },
  openRegisterPage: { zh: "打开注册页", en: "Open register page" },
  start: { zh: "启动", en: "Start" },
  stop: { zh: "停止", en: "Stop" },
  delete: { zh: "删除", en: "Delete" },
  selectBotFirst: { zh: "请先选择一个 Bot", en: "Select a bot first." },
  forwardingPolicy: { zh: "转发策略", en: "Forwarding Policy" },
  enableForwarding: { zh: "启用转发", en: "Enable forwarding" },
  allowedTargets: { zh: "允许目标", en: "Allowed targets" },
  savePolicy: { zh: "保存策略", en: "Save policy" },
  sessionHistory: { zh: "会话历史", en: "Session History" },
  noSessions: { zh: "该 Bot 暂无会话", en: "No sessions for this bot." },
  session: { zh: "会话", en: "Session" },
  prev: { zh: "上一页", en: "Prev" },
  next: { zh: "下一页", en: "Next" },
  page: { zh: "页", en: "Page" },
  time: { zh: "时间", en: "Time" },
  direction: { zh: "方向", en: "Direction" },
  from: { zh: "发送方", en: "From" },
  to: { zh: "接收方", en: "To" },
  type: { zh: "类型", en: "Type" },
  text: { zh: "内容", en: "Text" },
  unknownError: { zh: "未知错误", en: "Unknown error" },
  notAvailable: { zh: "无", en: "N/A" },
  backToOverview: { zh: "返回概览", en: "Back to overview" },
  logsPanel: { zh: "日志面板", en: "Logs Panel" },
  sessionLogs: { zh: "会话日志", en: "Session Logs" },
  systemLogs: { zh: "系统日志", en: "System Logs" },
  adminLogs: { zh: "后台日志", en: "Admin Logs" },
  workerLogs: { zh: "Worker 日志", en: "Worker Logs" },
  refreshLogs: { zh: "刷新日志", en: "Refresh logs" },
  noLogData: { zh: "暂无日志数据", en: "No log data." },
} as const;

export type TranslationKey = keyof typeof translations;

export function translate(language: UiLanguage, key: TranslationKey): string {
  return translations[key][language];
}
